---
version: '3.7'

networks:
  lan_access:
    driver: bridge

services:
  app:
    build: .
    container_name: server
    restart: always
    ports:
      - 5000:5000
    env_file: .env.development
    depends_on:
      - mongo
      - kafka
    links:
      - mongo
    networks:
      - lan_access
      - default
  app-consumer:
    build: .
    container_name: app-consumer-penalt-users
    restart: always
    env_file: .env.development
    command:
      - sh
      - -c
      - npm run consumer:penalt-users
    depends_on:
      - mongo
      - kafka
    links:
      - mongo
    networks:
      - lan_access
      - default
  mongo:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/var/lib/mongodb/data
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    restart: always
    networks: 
      - lan_access
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    restart: always
    networks: 
      - lan_access
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1